/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package stlc

import stlc.parser.Scanner
import java.io.StringReader

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(parse(Scanner(StringReader("let rec fact n = if (n == 0) 1 else fact(n - 1) * n in fact"))))
}
