name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  'stlc-deno':
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate parser and scanner
        run: |
          cd ./deno-stlc
          ./tasks/dev parser

      - name: Lint
        run: |
          cd ./deno-stlc
          deno lint

      - name: Formatting
        run: |
          cd ./deno-stlc
          deno fmt --check

      - name: Unit tests
        run: |
          cd ./deno-stlc
          deno test

  'stlc-kotlin':
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate parser and scanner
        run: |
          cd ./kotlin-stlc
          ./tasks/dev parser

      - name: Build
        run: |
          cd ./kotlin-stlc
          ./tasks/dev unit

  'tlca-deno':
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate parser and scanner
        run: |
          cd ./deno-tlca
          ./tasks/dev parser

      - name: Lint
        run: |
          cd ./deno-tlca
          deno lint

      - name: Formatting
        run: |
          cd ./deno-tlca
          deno fmt --check

      - name: Unit tests
        run: |
          cd ./deno-tlca
          deno test

  'tlca-kotlin':
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate parser and scanner
        run: |
          cd ./kotlin-tlca
          ./tasks/dev parser

      - name: Build
        run: |
          cd ./kotlin-tlca
          ./tasks/dev unit

