#!/bin/bash

PROJECT_HOME=$(dirname "$0")/..

build_jar() {
    echo "---| build JAR"
    cd "$PROJECT_HOME" || exit 1
    ./gradlew jar || exit 1
}

build_parser() {
    (
        echo "---| build parser"
        cd "$PROJECT_HOME" || exit 1

        mkdir -p "$PROJECT_HOME"/parser || exit 1

        deno run --allow-read --allow-write --allow-net --unsafely-ignore-certificate-errors \
            "https://raw.githubusercontent.com/littlelanguages/parspiler-cli/main/mod.ts" kotlin \
            --verbose \
            --directory=./app/src/main/kotlin \
            --package=tlca.parser \
            "$PROJECT_HOME"/../tlca/Grammar.llgd || exit 1
    )
}

scenario_tests() {
    echo "---| scenario tests"

    for FILE in "$PROJECT_HOME"/../tlca/scenarios/*.inp; do
        echo "- scenario test: $FILE"
        java -jar app/build/libs/app.jar "$FILE" > t.txt || exit 1

        if ! diff -q "$PROJECT_HOME"/../tlca/scenarios/$(basename "$FILE" .inp).out t.txt; then
            echo "scenario test failed: $FILE"
            diff "$PROJECT_HOME"/../tlca/scenarios/$(basename "$FILE" .inp).out t.txt
            rm t.txt
            exit 1
        fi

        rm t.txt
    done
}

unit_tests() {
    echo "---| unit tests"
    cd "$PROJECT_HOME" || exit 1
    ./gradlew test || exit 1
}

case "$1" in
"" | help)
    echo "Usage: $0 [<command>]"
    echo "Commands:"
    echo "  help"
    echo "    This help page"
    echo "  jar"
    echo "    Create the application's JAR file"
    echo "  parser"
    echo "    Builds the parser from specs"
    echo "  run"
    echo "    Run all tasks"
    echo "  scenario"
    echo "    Run all scenario tests"
    echo "  unit"
    echo "    Run all unit tests"
    ;;

run)
    build_parser
    unit_tests
    build_jar
    scenario_tests
    ;;

jar)
    build_jar
    ;;

parser)
    build_parser
    ;;

scenario)
    scenario_tests
    ;;

unit)
    unit_tests
    ;;

*)
    echo "$0: $1: Unknown command"
    exit 1
    ;;
esac
